version: '3'
services:
  api:
    image: krajewskim/python-api
    ports:
    - "5002:5002"
    environment: 
    - REDIS_HOST=redis
    depends_on: 
    - redis
  redis:
    image: "redis:alpine"

    